# Generated by Django 5.1.6 on 2025-02-07 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='form',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='form',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='form',
            name='description',
        ),
        migrations.RemoveField(
            model_name='form',
            name='title',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='data',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='form',
        ),
        migrations.AddField(
            model_name='form',
            name='name',
            field=models.CharField(default='default_name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='FormAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_access', to='api.project')),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='api.project'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='api.project')),
            ],
        ),
    ]
