# Generated by Django 5.1.6 on 2025-02-07 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_rename_submitted_at_submission_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='content',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='title',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='submission',
            name='data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.form'),
            preserve_default=False,
        ),
    ]
